language: python
python:
  - "2.7"
  - "3.5"
install:
  # We must explicitly install urllib3 into the virtualenv using pip here,
  # because setuptools' EasyInstall is not always able to install some
  # versions of urllib3. Partially explained here:
  # https://github.com/shazow/urllib3/issues/986
  - pip install urllib3

# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script: python setup.py test
